
name: Run Semantic release
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Setup the node environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # Cache dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # Install dependencies
      - run: npm ci --prefer-offline
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: master
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: test
          wait-interval: 20 # seconds
      - run: npm run publish
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT_SEMANTIC_RELEASE }}
